const contactsTypes = {
  GET_CONTACTS: 'GET_CONTACTS',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_FAILURE: 'GET_CONTACTS_FAILURE',

  REMOVE_CONTACT: 'REMOVE_CONTACT',
  REMOVE_CONTACT_SUCCESS: 'REMOVE_CONTACT_SUCCESS',
  REMOVE_CONTACT_FAILURE: 'REMOVE_CONTACT_FAILURE',

  ADD_CONTACT: 'ADD_CONTACT',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',

  EDIT_CONTACT_START: 'EDIT_CONTACT_START',
  EDIT_CONTACT_SEND: 'EDIT_CONTACT_SEND',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
  EDIT_CONTACT_FAILURE: 'EDIT_CONTACT_FAILURE',
  EDIT_CONTACT_RESET: 'EDIT_CONTACT_RESET',

  UPDATE_SEARCH_PARAMS: 'UPDATE_SEARCH_PARAMS',

  UPDATE_TOTAL: 'UPDATE_TOTAL',

  UPDATE_SEARCH_VALUE: 'UPDATE_SEARCH_VALUE',
}

export default contactsTypes;
